#!/bin/bash


# This is needed in .shrc
escape() {
    echo "\[$1\]"
}


. ~/.shrc


export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend


PROMPT_COMMAND=my_prompt


local_config="$HOME/.bashrc-local"
test -f "$local_config" && . "$local_config"


true
