#!/usr/bin/env bash

export LD_LIBRARY_PATH=$HOME/lib

extras=(
    $HOME/.nix-profile/bin
    $HOME/bin
    $HOME/terminal-dotfiles/bin
)
for extra in ${extras[*]}
do
    [[ -d "$extra" ]] \
 && [[ ":$PATH:" != *:"$extra":* ]] \
 && PATH="$extra:$PATH"
done
