#!/bin/sh

export TERM=xterm-256color
export AR_DIR=~/.archive
export MANPAGER="vim -c '%s/_\|.\|\[[0-9]*m//e' -c 'set nomodifiable nonumber buftype=nofile filetype=man' -"
export EDITOR=vim
export VISUAL=vim
export PAGER=less

alias vi=vim
alias view=vim
alias ls='ls -AFh --color'
alias grep='grep --binary-files=without-match --color'
alias locate='locate --basename --existing'
alias tmux="tmux attach"
alias screen="screen -DR"

path_extras="/sbin /usr/sbin /usr/local/sbin $HOME/bin"
for extra in $(echo $path_extras)
    do
    test -d $extra && test ":$PATH:" != "*:$extra:*" && PATH="$extra:$PATH"
done

my_cd() {
    "cd" "$@" && ls
}
alias cd="my_cd"

my_rm() {
    for arg in "$@"
    do
        # Move this thing to the archive
        thing=$(readlink -f "$arg")
        dest_dir="$AR_DIR"$(dirname "$thing")
        destination="$dest_dir/$(basename "$thing").$(date +'%Y-%m-%d_%H-%M-%S')"
        mkdir -p "$dest_dir"
        mv "$thing" "$destination"
        find "$destination" -type f -exec touch {} \;
    done
    # Clean up old and useless files and dirs
    find "$AR_DIR" -type f -mtime +7 -exec rm {} \;
    find "$AR_DIR" -type d -empty -exec rmdir {} \;
}
alias rm=my_rm
