#!/bin/zsh

# my_prompt in .shrc needs these stuff
prompt_escape() {
    echo "%{$1%}"
}
prompt_date='%D{%H:%M:%S}'
precmd_functions=(my_prompt)
. ~/.shrc

# When the default shell is Bash, if Konsole is configured to
# use Zsh, SHELL is set to Bash (???)
export SHELL="$0"

export HISTFILE=~/.zsh-history
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE
setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_LEX_WORDS
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY

setopt EXTENDED_GLOB

zstyle ':completion:*' use-cache on
autoload -U compinit
compinit

bindkey -e
bindkey "[3~"   delete-char
bindkey "OH"    beginning-of-line
bindkey "[H"    beginning-of-line
bindkey "[1~"   beginning-of-line
bindkey "[4~"   end-of-line
bindkey "[F"    end-of-line
bindkey "OF"    end-of-line
bindkey "[1;5C" forward-word
bindkey "[1;5D" backward-word

# Load local config if exists
local_config="$HOME/.zshrc-local"
test -f "$local_config" && . "$local_config"

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern line)
. ~/terminal-dotfiles/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Always return success
true
