" First thing first: pathogen to load everything
call pathogen#infect()


"" Functional options

" File type detection should have been on my default
filetype plugin indent on

" Some systems don't turn on syntax by default
syntax on

" Search as I type
set incsearch

" Case insensitive for searching
set ignorecase
" But allow for case sensitive when I seem to mean it
set smartcase

" Line numbers are good
set number

" Remove any trailing whitespace that is in the file
autocmd BufWrite * if ! &bin | silent! %s/\s\+$//ge | endif

" I don't mean Make, I mean Mako
autocmd BufRead *.mak set filetype=html

" Enable mouse support in console
set mouse=a

" Keep cursor in the middle of screen
set scrolloff=99

" Use + to copy to clipboard
let g:clipbrdDefaultReg = '+'

" Spaces no tabs
set expandtab
set tabstop=4
set shiftwidth=4

" Always show file info
set laststatus=2

" Show title
set title

" Lemme know what I'm doing
set showcmd
set report=0

" Be smart and try do indenting right
set autoindent
set smartindent
set preserveindent

" g as default flag for :substitute, make sense!
set gdefault


"" Display options

" We should have as many colors as possible!
set t_Co=256

" Transparent background too
autocmd ColorScheme * highlight Normal  ctermbg=None
autocmd ColorScheme * highlight NonText ctermbg=None

" Have a line indicate the cursor location
set cursorline

" My favorite color scheme, for now
colorscheme xoria256

" Highlight search results
set hlsearch


"" Key mappings

" Forgot to sudo when opening a file
cnoremap w!! w !sudo dd of=%

" Remap jj to escape in insert mode.
inoremap jj <Esc>

" Ctrl-jklm changes to that split
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l
nnoremap <c-h> <c-w>h

nnoremap <leader>c :set number!<CR>
nnoremap <leader>f :CtrlP<CR>
nnoremap <leader>h :set hlsearch!<CR>
nnoremap <leader>n :NERDTreeToggle<CR>
nnoremap <leader>p :set paste!<CR>
